# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integration/v1/nfe_key_integration_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='integration/v1/nfe_key_integration_api.proto',
  package='loggi.integration.v1',
  syntax='proto3',
  serialized_options=_b('\n\030com.loggi.integration.v1B\031NfeKeyIntegrationApiProtoP\001Z\rintegrationv1\242\002\003LIX\252\002\024Loggi.Integration.V1\312\002\024Loggi\\Integration\\V1'),
  serialized_pb=_b('\n,integration/v1/nfe_key_integration_api.proto\x12\x14loggi.integration.v1\x1a\x1cgoogle/api/annotations.proto\"M\n\x18NfeKeyIntegrationRequest\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\x0f\n\x07nfe_key\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61rcode\x18\x03 \x01(\t\"N\n\x19NfeKeyIntegrationResponse\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\x0f\n\x07nfe_key\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61rcode\x18\x03 \x01(\t2\xad\x01\n\x14NfeKeyIntegrationAPI\x12\x94\x01\n\x11NfeKeyIntegration\x12..loggi.integration.v1.NfeKeyIntegrationRequest\x1a/.loggi.integration.v1.NfeKeyIntegrationResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/inbound/nfekey-to-pkgBz\n\x18\x63om.loggi.integration.v1B\x19NfeKeyIntegrationApiProtoP\x01Z\rintegrationv1\xa2\x02\x03LIX\xaa\x02\x14Loggi.Integration.V1\xca\x02\x14Loggi\\Integration\\V1b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_NFEKEYINTEGRATIONREQUEST = _descriptor.Descriptor(
  name='NfeKeyIntegrationRequest',
  full_name='loggi.integration.v1.NfeKeyIntegrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company', full_name='loggi.integration.v1.NfeKeyIntegrationRequest.company', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nfe_key', full_name='loggi.integration.v1.NfeKeyIntegrationRequest.nfe_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='barcode', full_name='loggi.integration.v1.NfeKeyIntegrationRequest.barcode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=177,
)


_NFEKEYINTEGRATIONRESPONSE = _descriptor.Descriptor(
  name='NfeKeyIntegrationResponse',
  full_name='loggi.integration.v1.NfeKeyIntegrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company', full_name='loggi.integration.v1.NfeKeyIntegrationResponse.company', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nfe_key', full_name='loggi.integration.v1.NfeKeyIntegrationResponse.nfe_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='barcode', full_name='loggi.integration.v1.NfeKeyIntegrationResponse.barcode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=257,
)

DESCRIPTOR.message_types_by_name['NfeKeyIntegrationRequest'] = _NFEKEYINTEGRATIONREQUEST
DESCRIPTOR.message_types_by_name['NfeKeyIntegrationResponse'] = _NFEKEYINTEGRATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NfeKeyIntegrationRequest = _reflection.GeneratedProtocolMessageType('NfeKeyIntegrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NFEKEYINTEGRATIONREQUEST,
  '__module__' : 'integration.v1.nfe_key_integration_api_pb2'
  # @@protoc_insertion_point(class_scope:loggi.integration.v1.NfeKeyIntegrationRequest)
  })
_sym_db.RegisterMessage(NfeKeyIntegrationRequest)

NfeKeyIntegrationResponse = _reflection.GeneratedProtocolMessageType('NfeKeyIntegrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _NFEKEYINTEGRATIONRESPONSE,
  '__module__' : 'integration.v1.nfe_key_integration_api_pb2'
  # @@protoc_insertion_point(class_scope:loggi.integration.v1.NfeKeyIntegrationResponse)
  })
_sym_db.RegisterMessage(NfeKeyIntegrationResponse)


DESCRIPTOR._options = None

_NFEKEYINTEGRATIONAPI = _descriptor.ServiceDescriptor(
  name='NfeKeyIntegrationAPI',
  full_name='loggi.integration.v1.NfeKeyIntegrationAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=260,
  serialized_end=433,
  methods=[
  _descriptor.MethodDescriptor(
    name='NfeKeyIntegration',
    full_name='loggi.integration.v1.NfeKeyIntegrationAPI.NfeKeyIntegration',
    index=0,
    containing_service=None,
    input_type=_NFEKEYINTEGRATIONREQUEST,
    output_type=_NFEKEYINTEGRATIONRESPONSE,
    serialized_options=_b('\202\323\344\223\002\030\"\026/inbound/nfekey-to-pkg'),
  ),
])
_sym_db.RegisterServiceDescriptor(_NFEKEYINTEGRATIONAPI)

DESCRIPTOR.services_by_name['NfeKeyIntegrationAPI'] = _NFEKEYINTEGRATIONAPI

# @@protoc_insertion_point(module_scope)
