# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loggi_web/v1/transport_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loggi_web/v1/transport_type.proto',
  package='loggi.web.v1',
  syntax='proto3',
  serialized_options=_b('\n\020com.loggi.web.v1B\022TransportTypeProtoP\001Z\005webv1\242\002\003LWX\252\002\014Loggi.Web.V1\312\002\014Loggi\\Web\\V1'),
  serialized_pb=_b('\n!loggi_web/v1/transport_type.proto\x12\x0cloggi.web.v1*\x9a\x01\n\rTransportType\x12\x1a\n\x16TRANSPORT_TYPE_INVALID\x10\x00\x12\x1d\n\x19TRANSPORT_TYPE_MOTORCYCLE\x10\x01\x12\x1e\n\x16TRANSPORT_TYPE_BICYCLE\x10\x02\x1a\x02\x08\x01\x12\x16\n\x12TRANSPORT_TYPE_VAN\x10\x03\x12\x16\n\x12TRANSPORT_TYPE_CAR\x10\x04*c\n\x0eProductVersion\x12\x1b\n\x17PRODUCT_VERSION_INVALID\x10\x00\x12\x19\n\x15PRODUCT_VERSION_PRIME\x10\x01\x12\x19\n\x15PRODUCT_VERSION_START\x10\x02\x42S\n\x10\x63om.loggi.web.v1B\x12TransportTypeProtoP\x01Z\x05webv1\xa2\x02\x03LWX\xaa\x02\x0cLoggi.Web.V1\xca\x02\x0cLoggi\\Web\\V1b\x06proto3')
)

_TRANSPORTTYPE = _descriptor.EnumDescriptor(
  name='TransportType',
  full_name='loggi.web.v1.TransportType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSPORT_TYPE_INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPORT_TYPE_MOTORCYCLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPORT_TYPE_BICYCLE', index=2, number=2,
      serialized_options=_b('\010\001'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPORT_TYPE_VAN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPORT_TYPE_CAR', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=52,
  serialized_end=206,
)
_sym_db.RegisterEnumDescriptor(_TRANSPORTTYPE)

TransportType = enum_type_wrapper.EnumTypeWrapper(_TRANSPORTTYPE)
_PRODUCTVERSION = _descriptor.EnumDescriptor(
  name='ProductVersion',
  full_name='loggi.web.v1.ProductVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRODUCT_VERSION_INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCT_VERSION_PRIME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCT_VERSION_START', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=208,
  serialized_end=307,
)
_sym_db.RegisterEnumDescriptor(_PRODUCTVERSION)

ProductVersion = enum_type_wrapper.EnumTypeWrapper(_PRODUCTVERSION)
TRANSPORT_TYPE_INVALID = 0
TRANSPORT_TYPE_MOTORCYCLE = 1
TRANSPORT_TYPE_BICYCLE = 2
TRANSPORT_TYPE_VAN = 3
TRANSPORT_TYPE_CAR = 4
PRODUCT_VERSION_INVALID = 0
PRODUCT_VERSION_PRIME = 1
PRODUCT_VERSION_START = 2


DESCRIPTOR.enum_types_by_name['TransportType'] = _TRANSPORTTYPE
DESCRIPTOR.enum_types_by_name['ProductVersion'] = _PRODUCTVERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
_TRANSPORTTYPE.values_by_name["TRANSPORT_TYPE_BICYCLE"]._options = None
# @@protoc_insertion_point(module_scope)
