# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postalcodetable/v2/city_rr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='postalcodetable/v2/city_rr.proto',
  package='loggi.postalcodetable.v2',
  syntax='proto3',
  serialized_options=_b('\n\034com.loggi.postalcodetable.v2B\013CityRrProtoP\001Z\021postalcodetablev2\242\002\003LPX\252\002\030Loggi.Postalcodetable.V2\312\002\030Loggi\\Postalcodetable\\V2'),
  serialized_pb=_b('\n postalcodetable/v2/city_rr.proto\x12\x18loggi.postalcodetable.v2*\xe8\x03\n\x06\x43ityRr\x12\x13\n\x0f\x43ITY_RR_INVALID\x10\x00\x12\x18\n\x13\x43ITY_RR_ALTO_ALEGRE\x10\xcd\x39\x12\x14\n\x0f\x43ITY_RR_AMAJARI\x10\xce\x39\x12\x16\n\x11\x43ITY_RR_BOA_VISTA\x10\xcf\x39\x12\x13\n\x0e\x43ITY_RR_BONFIM\x10\xd0\x39\x12\x12\n\rCITY_RR_CANTA\x10\xd1\x39\x12\x16\n\x11\x43ITY_RR_CARACARAI\x10\xd2\x39\x12\x14\n\x0f\x43ITY_RR_CAROEBE\x10\xd3\x39\x12\x18\n\x13\x43ITY_RR_FELIX_PINTO\x10\xeeT\x12\x14\n\x0f\x43ITY_RR_IRACEMA\x10\xd4\x39\x12\x14\n\x0f\x43ITY_RR_MUCAJAI\x10\xd5\x39\x12\x16\n\x11\x43ITY_RR_NORMANDIA\x10\xd6\x39\x12\x19\n\x14\x43ITY_RR_NOVO_PARAISO\x10\xf0T\x12\x16\n\x11\x43ITY_RR_PACARAIMA\x10\xd7\x39\x12\x19\n\x14\x43ITY_RR_RORAINOPOLIS\x10\xd8\x39\x12\x1a\n\x15\x43ITY_RR_SANTA_CECILIA\x10\xedT\x12\x1f\n\x1a\x43ITY_RR_SAO_JOAO_DA_BALIZA\x10\xd9\x39\x12\x15\n\x10\x43ITY_RR_SAO_LUIZ\x10\xda\x39\x12\x13\n\x0e\x43ITY_RR_TABOCA\x10\xefT\x12\x15\n\x10\x43ITY_RR_UIRAMUTA\x10\xdb\x39\x42|\n\x1c\x63om.loggi.postalcodetable.v2B\x0b\x43ityRrProtoP\x01Z\x11postalcodetablev2\xa2\x02\x03LPX\xaa\x02\x18Loggi.Postalcodetable.V2\xca\x02\x18Loggi\\Postalcodetable\\V2b\x06proto3')
)

_CITYRR = _descriptor.EnumDescriptor(
  name='CityRr',
  full_name='loggi.postalcodetable.v2.CityRr',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_ALTO_ALEGRE', index=1, number=7373,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_AMAJARI', index=2, number=7374,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_BOA_VISTA', index=3, number=7375,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_BONFIM', index=4, number=7376,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_CANTA', index=5, number=7377,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_CARACARAI', index=6, number=7378,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_CAROEBE', index=7, number=7379,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_FELIX_PINTO', index=8, number=10862,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_IRACEMA', index=9, number=7380,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_MUCAJAI', index=10, number=7381,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_NORMANDIA', index=11, number=7382,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_NOVO_PARAISO', index=12, number=10864,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_PACARAIMA', index=13, number=7383,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_RORAINOPOLIS', index=14, number=7384,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_SANTA_CECILIA', index=15, number=10861,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_SAO_JOAO_DA_BALIZA', index=16, number=7385,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_SAO_LUIZ', index=17, number=7386,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_TABOCA', index=18, number=10863,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_RR_UIRAMUTA', index=19, number=7387,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=63,
  serialized_end=551,
)
_sym_db.RegisterEnumDescriptor(_CITYRR)

CityRr = enum_type_wrapper.EnumTypeWrapper(_CITYRR)
CITY_RR_INVALID = 0
CITY_RR_ALTO_ALEGRE = 7373
CITY_RR_AMAJARI = 7374
CITY_RR_BOA_VISTA = 7375
CITY_RR_BONFIM = 7376
CITY_RR_CANTA = 7377
CITY_RR_CARACARAI = 7378
CITY_RR_CAROEBE = 7379
CITY_RR_FELIX_PINTO = 10862
CITY_RR_IRACEMA = 7380
CITY_RR_MUCAJAI = 7381
CITY_RR_NORMANDIA = 7382
CITY_RR_NOVO_PARAISO = 10864
CITY_RR_PACARAIMA = 7383
CITY_RR_RORAINOPOLIS = 7384
CITY_RR_SANTA_CECILIA = 10861
CITY_RR_SAO_JOAO_DA_BALIZA = 7385
CITY_RR_SAO_LUIZ = 7386
CITY_RR_TABOCA = 10863
CITY_RR_UIRAMUTA = 7387


DESCRIPTOR.enum_types_by_name['CityRr'] = _CITYRR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
